In [27]:
import numpy as np

In [28]:
l= [1,2,3,4]

In [29]:
ar= np.array(l)

In [4]:
type(ar)

numpy.ndarray

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
np.array([[1,2], [4,5]])

array([[1, 2],
       [4, 5]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
a= [4,5,6]

In [9]:
np.asanyarray(a)

array([4, 5, 6])

In [10]:
#always bydefault 2d hota hai
#matrix is subset of array. array become superclass in numpy

b= np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4]])

In [14]:
#asanyarray kisi bhi array ke form me change karta hai
#matrix ko dala asanyarray ke andar to change nahi kiya as it is chod diya bcoz matrix to bydefault suset of array hai
#to matrix ki kadhi hi overt nahi karne vala
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [15]:
a= np.array(l)

In [23]:
#swollo coly
c= a

In [17]:
c

array([1, 2, 3, 4])

In [18]:
a

array([1, 2, 3, 4])

In [19]:
c[0]

1

In [20]:
c[0] = 100

In [21]:
c

array([100,   2,   3,   4])

In [22]:
a

array([100,   2,   3,   4])

In [24]:
d= np.copy(a)

In [25]:
d

array([100,   2,   3,   4])

In [29]:
a[1]= 300

In [30]:
a

array([100, 300,  30,   4])

In [31]:
d

array([100,   2,   3,   4])

In [32]:
np.fromfunction(lambda i, j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i, j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [36]:
iterable= (i*i for i in range(5))

In [37]:
iterable

<generator object <genexpr> at 0x7f6f8c0e7680>

In [39]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [46]:
np.fromstring('600  800', sep='')

/tmp/ipykernel_77/2493730236.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring('600  800', sep='')


array([1.40072092e-76])

In [49]:
np.fromstring('4,5' , sep=',')

array([4., 5.])

In [51]:
#datatype in numpy

In [53]:
e= [11,22,33,44,55]

In [55]:
ar= np.array(e)

In [57]:
#to check dia of e array
ar.ndim

1

In [61]:
ar2= np.array([[1,2,3,4],[5,6,7,8,]])

In [63]:
ar2.ndim

2

In [64]:
ar.size

5

In [65]:
ar2.size

8

In [66]:
ar.shape

(5,)

In [67]:
ar2.shape

(2, 4)

In [71]:
ar.dtype

dtype('int64')

In [72]:
ar2.dtype

dtype('int64')

In [76]:
#ek ka date type floating pt hai to uske chalte sare ka  kar diya
ar22= np.array([[1.45,4,76],[23,45,66]])

In [75]:
ar22

array([[ 1.45,  4.  , 76.  ],
       [23.  , 45.  , 66.  ]])

In [77]:
ar22.dtype

dtype('float64')

In [78]:
range(5)

range(0, 5)

In [80]:
# if ask toproduce flt pt in range so nahidega coz range only give int
#jump size vo dena hai fractionalnum to vo bhi nahi de sakte
list(range(5))

[0, 1, 2, 3, 4]

In [81]:
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [83]:
#so numpy ke andar already provision hai jaha par aap floating as starting pt,end pt or even as a jump size

In [84]:
np.arange(1.1,4.4)

array([1.1, 2.1, 3.1, 4.1])

In [79]:
#gave jum as 3
np.arange(1.1,4.4,.3)

array([1.1, 1.4, 1.7, 2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4])

In [87]:
#upar valadata jo produce kiya hai use list me convert karna hai
list(np.arange(1.1,4.4,.3))

[1.1,
 1.4000000000000001,
 1.7000000000000002,
 2.0,
 2.3000000000000003,
 2.6000000000000005,
 2.9000000000000004,
 3.2000000000000006,
 3.5000000000000004,
 3.8000000000000003,
 4.1000000000000005,
 4.4]

In [90]:
#produce 10 data in between 1-5 scale
#1-5 le liya ek line us line ko divide kiya 10 equal s[pace me
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [94]:
#5 data leke array produce karo
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [93]:
#it is 2D coz 3 row 5columns
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [105]:
#3D
#3 MATRIX  5ROW  2 COLUMNS
#READ AS :- we have 5 cross 2 ,3 such kind of arrays
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [109]:
#4D #READ AS we have 2 cross 4 5 such matrix is tarah se 3 hai
#2 row 4 columns aise 5 hai and 5 jaise set 3 hai
#4d but cannot visualize on graph
ar4= np.zeros((3,5,2,4))

In [107]:
ar4.ndim

4

In [108]:
ar4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [2]:
np.ones(1)

array([1.])

In [3]:
np.ones(4)

array([1., 1., 1., 1.])

In [6]:
#2 ROW 3 COLUMNS
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#2 MATRI 3 ROW  ,2COLUMS
ON= np.ones((2,3,2))

In [12]:
ON

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [14]:
# ADD 5 IN EVERY  VALUE
ON+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [15]:
ON*5

array([[[5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.]]])

In [6]:
#creat empty array . can se value but it is negligible
np.empty((3,5))

array([[4.68529483e-310, 5.98149210e-154, 3.03338118e-067,
        1.05248921e-153, 4.56335221e-072],
       [6.01347002e-154, 1.05191681e-153, 8.41789903e-053,
        1.95360725e-109, 5.28595595e-085],
       [6.45757112e+270, 1.50761622e+161, 5.50422964e+257,
        4.83245960e+276, 1.05132385e-153]])

In [3]:
np.empty((3,4))

array([[4.68529438e-310, 0.00000000e+000, 1.01855798e-312,
        9.54898106e-313],
       [1.14587773e-312, 1.03977794e-312, 1.23075756e-312,
        1.06099790e-312],
       [1.06099790e-312, 9.76118064e-313, 1.16709769e-312,
        1.90979621e-312]])

In [5]:
np.empty((3,6))

array([[4.68529483e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 5.98149210e-154, 3.03338118e-067],
       [1.05248921e-153, 4.56335221e-072, 6.01347002e-154,
        1.05191681e-153, 8.41789903e-053, 1.95360725e-109],
       [5.28595595e-085, 6.45757112e+270, 1.50761622e+161,
        5.50422964e+257, 4.83245960e+276, 1.05132385e-153]])

In [11]:
#square matrix,same diamension, determinant 1 hota hai, and diagonal me hamesha 11111 hota hai
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.eye(3,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [15]:
#linespace
# 20 data chahiye between 2-4 in equal interval
#2-4 e line ko lega and 0 times / karega
np.linspace(2,4 , 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [19]:
#logspace
#start 2 se end5, kitna data chahiye so 10 data and subka logarithm nikal ke de dega between 2-5 line
#same as linespace only diff is log nikalke de raha hai 
np.logspace(2,5 , 10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [21]:
#base is 0 and want to change base
np.logspace(2,5 , 10, base =2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [22]:
#RANDOM FUNCTION

In [32]:
"""diff between randn and rand:-random value in a given shape: return a sample form the 'standard normal ' distributionm respectivey.RAND only produce array. 'randn' aisa data generate karega jaha par data ka mean = 0 and SD =1 IS CALLED AS STANDARD NORMAL DISTRIBUTION."""

"diff between randn and rand:-random value in a given shape: return a sample form the 'standard normal ' distributionm respectivey.RAND only produce array. 'randn' aisa data generate karega jaha par data ka mean = 0 and SD =1 IS CALLED AS STANDARD NORMAL DISTRIBUTION."

In [25]:
#generate random data 3ROW 4 COLUMN
arr= np.random.randn(3,4)

In [26]:
    arr

array([[ 1.63369622, -1.01703323,  1.20337823,  0.54404613],
       [ 0.94443061, -0.64326624, -0.35201509,  0.71672093],
       [ 0.01449701,  0.02881531, -0.53347453, -1.35547244]])

In [27]:
import pandas as pd

In [28]:
pd.DataFrame(arr)

0         1         2         3
0  1.633696 -1.017033  1.203378  0.544046
1  0.944431 -0.643266 -0.352015  0.716721
2  0.014497  0.028815 -0.533475 -1.355472

In [29]:
np.random.rand(3,4)

array([[0.60040559, 0.9782073 , 0.80607521, 0.39946161],
       [0.60939996, 0.71316584, 0.27752801, 0.33826774],
       [0.60198398, 0.59713385, 0.47539622, 0.14732293]])

In [36]:
#randin= int hi produce karta hai. data nikalke do 1-110 ke bich me int do. data nikalke do 3cross 4 ka
np.random.randint(1,110,(3,4))

array([[50, 69, 33, 35],
       [92, 53, 96, 14],
       [44, 26, 86, 24]])

In [37]:
#300 row 400 columns
np.random.randint(1,110,(300,400))

array([[ 23,  48,  70, ...,  27,  84,  54],
       [ 83,  68,  88, ...,  25, 104,  47],
       [ 19,  78,  78, ...,  89,  98,  87],
       ...,
       [100,  33,  76, ...,  86,  35, 107],
       [ 22,  46,  42, ...,  55,  22,  56],
       [ 94,  23,  24, ...,   5,  37,  49]])

In [39]:
#convert this into datarame
pd.DataFrame(np.random.randint(1,110,(300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     21   31   18    3   88   79   11   51    7   30  ...   45   63   98   
1     96    5   41    4   19   78   33   29    8  101  ...   47   58   59   
2     76   18   70   74   14   45   50   36   44   58  ...   26   32    1   
3     43   58   55    3   84   19   90   72   15   17  ...  101   38  104   
4      4   20   73  106   95    6   51   72   26   80  ...   20   37   23   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   78   44   46   85   40  105   35   11  106   44  ...   75   61   85   
296   32   46    1   82   59   28   86   43  104   74  ...   38    7   44   
297   72   44    7   24   98   97    6   44   28   13  ...   96   98    6   
298   65   70   47    8   79   18   12   82   74   95  ...   83   65   92   
299   99   71  109  100  108    4   87   41   37   31  ...   64   22   69   

     393  394  395  396  397  398  399  
0    102   47   33    9   44   13   67  
1     21   55   86   92   72   78   25  
2     62   18   10   67   54   90   15  
3     44   44    6   16   71   75  109  
4     38   38   56   41  101   37   75  
..   ...  ...  ...  ...  ...  ...  ...  
295   55   92    9   31    7   15   24  
296   90   71   89  101   75    4   87  
297   66   39   79   65   76   92   71  
298   81   26  107   32   60   90   87  
299   68   82   17   99  101   22   77  

[300 rows x 400 columns]

In [40]:
#can store this too
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv("test.csv")

In [41]:
arr = np.random.rand(3,4)

In [42]:
arr

array([[0.48639165, 0.38409108, 0.76979264, 0.59766479],
       [0.94562373, 0.70073822, 0.87727591, 0.84661373],
       [0.36843846, 0.18980989, 0.87428786, 0.58449461]])

In [44]:
#total 12 data hai if want to change /convert into another shape
#data hai 12 to jo bhi reshape ke andar doge vo  multiple of total data(12) hona chahiye
arr.reshape(6,2)

array([[0.48639165, 0.38409108],
       [0.76979264, 0.59766479],
       [0.94562373, 0.70073822],
       [0.87727591, 0.84661373],
       [0.36843846, 0.18980989],
       [0.87428786, 0.58449461]])

In [45]:
arr.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [48]:
arr.reshape(6,-1)
#-1 matlab ek diamention khud se samajh raha hai. koi bhi -value do ek dim 6 hai and 2nd is 2 bcoz data is 1

array([[0.48639165, 0.38409108],
       [0.76979264, 0.59766479],
       [0.94562373, 0.70073822],
       [0.87727591, 0.84661373],
       [0.36843846, 0.18980989],
       [0.87428786, 0.58449461]])

In [49]:
arr1= arr.reshape(6,-1323)

In [50]:
arr1

array([[0.48639165, 0.38409108],
       [0.76979264, 0.59766479],
       [0.94562373, 0.70073822],
       [0.87727591, 0.84661373],
       [0.36843846, 0.18980989],
       [0.87428786, 0.58449461]])

In [53]:
#want to extract specific data from set so indexing,slicing opration
#column 2 index5
#want to extract data of 1st row 1st column
arr1[1]

array([0.76979264, 0.59766479])

In [54]:
arr1[1][1]

0.5976647907344192

In [65]:
#want to extract random values  s/a  0.84661373,, 0.18980989, 0.58449461
arr1[3:6]

array([[0.87727591, 0.84661373],
       [0.36843846, 0.18980989],
       [0.87428786, 0.58449461]])

In [66]:
#[row,colum]
arr1[3:6,1]

array([0.84661373, 0.18980989, 0.58449461])

In [3]:
#data nikalo from/between 1-100 5cross 5 ka array 5row,5 column
arr= np.random.randint(1,100,(5,5))

In [4]:
arr

array([[87, 82, 63, 51, 37],
       [98, 66,  4, 83, 28],
       [ 3, 23, 23, 90, 76],
       [91, 92, 46, 76, 27],
       [80, 26, 85, 54, 40]])

In [5]:
#conditional 
#only greater than 25 data nikalo
arr>25
#jaha par greater than 25 hai vaha true nahi hai vaha false hence to see value

array([[ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [6]:
arr[arr>25]

array([87, 82, 63, 51, 37, 98, 66, 83, 28, 90, 76, 91, 92, 46, 76, 27, 80,
       26, 85, 54, 40])

In [7]:
arr

array([[87, 82, 63, 51, 37],
       [98, 66,  4, 83, 28],
       [ 3, 23, 23, 90, 76],
       [91, 92, 46, 76, 27],
       [80, 26, 85, 54, 40]])

In [10]:
arr[2:4,[1,2]]

array([[23, 23],
       [92, 46]])

In [11]:
arr[0][0]

87

In [14]:
#manupulate data
arr[0][0]=500

In [15]:
arr

array([[500,  82,  63,  51,  37],
       [ 98,  66,   4,  83,  28],
       [  3,  23,  23,  90,  76],
       [ 91,  92,  46,  76,  27],
       [ 80,  26,  85,  54,  40]])

In [16]:
arr1= np.random.randint(1,3,(3,3))
arr2= np.random.randint(1,3,(3,3))

In [17]:
arr1

array([[2, 1, 1],
       [1, 1, 1],
       [2, 1, 2]])

In [18]:
arr2

array([[2, 1, 2],
       [1, 1, 2],
       [2, 2, 2]])

In [23]:
#index  vise + not matrix vise
arr1+arr2

array([[4, 2, 3],
       [2, 2, 3],
       [4, 3, 4]])

In [20]:
arr1-arr2

array([[ 0,  0, -1],
       [ 0,  0, -1],
       [ 0, -1,  0]])

In [21]:
arr1*arr2

array([[4, 1, 2],
       [1, 1, 2],
       [4, 2, 4]])

In [22]:
arr1/arr2

array([[1. , 1. , 0.5],
       [1. , 1. , 0.5],
       [1. , 0.5, 1. ]])

In [24]:
#matrix vise multiplication
arr1@arr2

array([[ 7,  5,  8],
       [ 5,  4,  6],
       [ 9,  7, 10]])

In [27]:
arr1/0

/tmp/ipykernel_77/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [28]:
arr1+100

array([[102, 101, 101],
       [101, 101, 101],
       [102, 101, 102]])

In [29]:
arr1**2

array([[4, 1, 1],
       [1, 1, 1],
       [4, 1, 4]])

In [31]:
#broadcating
arrr= np.zeros((4,4))

In [32]:
arrr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
row= np.array([1,2,3,4])

In [34]:
row

array([1, 2, 3, 4])

In [35]:
arrr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [38]:
#add by column vise
#TRanspose.1d GHUMEGA nahi 2D GHUM SAKTA AI
row.T

array([1, 2, 3, 4])

In [39]:
col= np.array([[1, 2, 3, 4]])

In [40]:
col

array([[1, 2, 3, 4]])

In [42]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [44]:
col

array([[1, 2, 3, 4]])

In [46]:
arr1=np.random.randint(1,4(3,4))

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
/tmp/ipykernel_77/2945069087.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  arr1=np.random.randint(1,4(3,4))
/tmp/ipykernel_77/2945069087.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  arr1=np.random.randint(1,4(3,4))
/tmp/ipykernel_77/2945069087.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  arr1=np.random.randint(1,4(3,4))
/tmp/ipykernel_77/2945069087.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  arr1=np.random.randint(1,4(3,4))


TypeError: 'int' object is not callable

In [1]:
########### LECTURE 2 #####

In [9]:
import numpy as np
import pandas as pd

In [20]:
ar= np.random.randint(1,10,(3,4))

In [11]:
ar

array([[2, 2, 6, 8],
       [9, 6, 4, 6],
       [1, 8, 2, 6]])

In [13]:
 pd.DataFrame(ar)

0  1  2  3
0  2  2  6  8
1  9  6  4  6
2  1  8  2  6

In [15]:
ar.reshape(6,2)

array([[2, 2],
       [6, 8],
       [9, 6],
       [4, 6],
       [1, 8],
       [2, 6]])

In [16]:
ar.reshape(2,6)

array([[2, 2, 6, 8, 9, 6],
       [4, 6, 1, 8, 2, 6]])

In [17]:
ar.reshape(2,-2423)

array([[2, 2, 6, 8, 9, 6],
       [4, 6, 1, 8, 2, 6]])

In [20]:
#Transpose
ar.T

array([[2, 9, 1],
       [2, 6, 8],
       [6, 4, 2],
       [8, 6, 6]])

In [21]:
ar

array([[2, 2, 6, 8],
       [9, 6, 4, 6],
       [1, 8, 2, 6]])

In [22]:
#jo bhi data hai usko 1D me convert karta hai. 
ar.flatten()

array([2, 2, 6, 8, 9, 6, 4, 6, 1, 8, 2, 6])

In [24]:
ar1= np.array([1,2,3,4])

In [25]:
ar1.ndim

1

In [28]:
#expand _dims = ar1 1D array tha usko 2D ME  CONVERT KAREGA [] YE 1 THA USKO [[]] KIYA MEANS 2D
np.expand_dims(ar1, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [29]:
np.expand_dims(ar1, axis=0)

array([[1, 2, 3, 4]])

In [32]:
#2d array
ar

array([[2, 2, 6, 8],
       [9, 6, 4, 6],
       [1, 8, 2, 6]])

In [33]:
np.squeeze(ar)

array([[2, 2, 6, 8],
       [9, 6, 4, 6],
       [1, 8, 2, 6]])

In [34]:
data= np.array([[1],[2],[3],[4]])

In [35]:
data

array([[1],
       [2],
       [3],
       [4]])

In [40]:
#([[1],[2],[3],[4]]) 2D tha usko 1D kiya sabko squeeze
np.squeeze(data)

array([1, 2, 3, 4])

In [41]:
ar1

array([1, 2, 3, 4])

In [44]:
# ar1 ke andar jo bhi element hai usko 3 times repeat kar diya
np.repeat(ar1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [50]:
#2 is shift parameter
#1 jo tha vo 0 pe available tha so 0+1, 2 1 pe available tha in index so 2+1 and so on
np.roll(ar1 , 2)

array([3, 4, 1, 2])

In [47]:
ar1

array([1, 2, 3, 4])

In [53]:
#2D matrix banayega and apne data ko diagonally pass karega numbers
np.diag(ar1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [54]:
###BINARY OPRATIONS IN NUMPY

In [62]:
ar2= np.random.randint(1,10,(3,4))

In [59]:
ar

array([[2, 2, 6, 8],
       [9, 6, 4, 6],
       [1, 8, 2, 6]])

In [63]:
ar2

array([[9, 6, 9, 6],
       [5, 5, 5, 6],
       [1, 1, 8, 5]])

In [65]:
#index vise opration karega +
ar+ar2

array([[11,  8, 15, 14],
       [14, 11,  9, 12],
       [ 2,  9, 10, 11]])

In [66]:
ar*ar2

array([[18, 12, 54, 48],
       [45, 30, 20, 36],
       [ 1,  8, 16, 30]])

In [67]:
ar/ar2

array([[0.22222222, 0.33333333, 0.66666667, 1.33333333],
       [1.8       , 1.2       , 0.8       , 1.        ],
       [1.        , 8.        , 0.25      , 1.2       ]])

In [68]:
ar-ar2

array([[-7, -4, -3,  2],
       [ 4,  1, -1,  0],
       [ 0,  7, -6,  1]])

In [69]:
ar%ar2

array([[2, 2, 6, 2],
       [4, 1, 4, 0],
       [0, 0, 2, 1]])

In [73]:
#for power
ar**ar2

array([[     512,       64, 10077696,   262144],
       [   59049,     7776,     1024,    46656],
       [       1,        8,      256,     7776]])

In [75]:
#ar2 ka -
~ar2

array([[-10,  -7, -10,  -7],
       [ -6,  -6,  -6,  -7],
       [ -2,  -2,  -9,  -6]])

In [77]:
#or opration
ar|ar2

array([[11,  6, 15, 14],
       [13,  7,  5,  6],
       [ 1,  9, 10,  7]])

In [78]:
ar>ar2

array([[False, False, False,  True],
       [ True,  True, False, False],
       [False,  True, False,  True]])

In [82]:
#Numpy- string function
np.array(['samidha''subhane'])

array(['samidhasubhane'], dtype='<U14')

In [84]:
ar3= np.array(['samidha','subhane'])

In [86]:
#convert uppercase
np.char.upper(ar3)

array(['SAMIDHA', 'SUBHANE'], dtype='<U7')

In [87]:
np.char.title(ar3)

array(['Samidha', 'Subhane'], dtype='<U7')

In [88]:
np.char.capitalize(ar3)

array(['Samidha', 'Subhane'], dtype='<U7')

In [89]:
np.char.lower(ar3)

array(['samidha', 'subhane'], dtype='<U7')

In [92]:
np.char.center(ar3,5)

array(['samid', 'subha'], dtype='<U5')

In [94]:
####Numpy Mathematical function

In [96]:
ar

array([[2, 2, 6, 8],
       [9, 6, 4, 6],
       [1, 8, 2, 6]])

In [97]:
np.sin(ar)

array([[ 0.90929743,  0.90929743, -0.2794155 ,  0.98935825],
       [ 0.41211849, -0.2794155 , -0.7568025 , -0.2794155 ],
       [ 0.84147098,  0.98935825,  0.90929743, -0.2794155 ]])

In [98]:
np.cos(ar)

array([[-0.41614684, -0.41614684,  0.96017029, -0.14550003],
       [-0.91113026,  0.96017029, -0.65364362,  0.96017029],
       [ 0.54030231, -0.14550003, -0.41614684,  0.96017029]])

In [99]:
np.tanh(ar)

array([[0.96402758, 0.96402758, 0.99998771, 0.99999977],
       [0.99999997, 0.99998771, 0.9993293 , 0.99998771],
       [0.76159416, 0.99999977, 0.96402758, 0.99998771]])

In [100]:
np.tanh(ar).T

array([[0.96402758, 0.99999997, 0.76159416],
       [0.96402758, 0.99998771, 0.99999977],
       [0.99998771, 0.9993293 , 0.96402758],
       [0.99999977, 0.99998771, 0.99998771]])

In [101]:
np.log10(ar)

array([[0.30103   , 0.30103   , 0.77815125, 0.90308999],
       [0.95424251, 0.77815125, 0.60205999, 0.77815125],
       [0.        , 0.90308999, 0.30103   , 0.77815125]])

In [102]:
#exponent
np.exp(ar)

array([[7.38905610e+00, 7.38905610e+00, 4.03428793e+02, 2.98095799e+03],
       [8.10308393e+03, 4.03428793e+02, 5.45981500e+01, 4.03428793e+02],
       [2.71828183e+00, 2.98095799e+03, 7.38905610e+00, 4.03428793e+02]])

In [103]:
#square root
np.sqrt(ar)

array([[1.41421356, 1.41421356, 2.44948974, 2.82842712],
       [3.        , 2.44948974, 2.        , 2.44948974],
       [1.        , 2.82842712, 1.41421356, 2.44948974]])

In [105]:
np.power(ar,2)

array([[ 4,  4, 36, 64],
       [81, 36, 16, 36],
       [ 1, 64,  4, 36]])

In [106]:
np.mean(ar)

5.0

In [109]:
np.mod(ar,3)

array([[2, 2, 0, 2],
       [0, 0, 1, 0],
       [1, 2, 2, 0]])

In [110]:
np.median(ar)

6.0

In [112]:
np.std(ar)

2.614064523559687

In [113]:
np.var(ar)

6.833333333333333

In [114]:
np.min(ar)

1

In [115]:
np.max(ar)

9

In [2]:
####LECTURE 3

In [3]:
#SORT ,SEARCH & COUNTING Function

In [1]:
import numpy as np

In [30]:
arr4= np.array([2,3,4,22,7,6,9,5,7,8])

In [9]:
arr4

array([ 2,  3,  4, 22,  7,  6,  9,  5,  7,  8])

In [5]:
#ascending order sort
np.sort(arr4)

array([ 2,  3,  4,  5,  6,  7,  7,  8,  9, 22])

In [8]:
#arr4 array ke andar 34 ko kaha daal sakte hai?konse location par jayega so 10th index ke upar
np.searchsorted(arr4, 34)

10

In [10]:
arr5 = np.array([0,345,454,0,0,0,0,0])

In [12]:
#want to know kitne non zero data hai
np.count_nonzero(arr5)

2

In [15]:
arr5

array([  0, 345, 454,   0,   0,   0,   0,   0])

In [14]:
#filter More than 6 DATA AUR USKA KYA INDEX HAI,KIS JAGAH PAR VO AVAILABLE HAI
#GREATER THAN DATA ON WHIH INDEX TOH-
np.where(arr4>6)

(array([3, 4, 6, 8, 9]),)

In [18]:
#WANT TO EXTRACT DATA BASE ON CONDITION greater than 6 so;-
np.extract(arr5>3,arr5)

array([345, 454])

In [22]:
np.extract(ar>3,ar)

array([4, 8, 4, 4, 4, 8, 6, 6, 8])

In [25]:
#byte swapping
arr4

array([ 2,  3,  4, 22,  7,  6,  9,  5,  7,  8])

In [26]:
arr4.byteswap()

array([ 144115188075855872,  216172782113783808,  288230376151711744,
       1585267068834414592,  504403158265495552,  432345564227567616,
        648518346341351424,  360287970189639680,  504403158265495552,
        576460752303423488])

In [ ]:


#COPIES  & VIEW

In [35]:
a= arr4.copy()
#or
b= np.copy(arr4)

In [34]:
a

array([ 2,  3,  4, 22,  7,  6,  9,  5,  7,  8])

In [36]:
b

array([ 2,  3,  4, 22,  7,  6,  9,  5,  7,  8])

In [47]:
####swollo copy concept. changes get permenent
##koi new data nahi banata, koi ne
c= arr4.view()

In [43]:
c

array([ 2,  3,  4, 22,  7,  6,  9,  5,  7,  8])

In [44]:
c[0]= 67

In [45]:
c

array([67,  3,  4, 22,  7,  6,  9,  5,  7,  8])

In [46]:
arr4

array([67,  3,  4, 22,  7,  6,  9,  5,  7,  8])

In [53]:


#same implimentation as numpy

### Matrix librery

In [54]:
import numpy.matlib as nm


In [55]:
#it generetes matrix in this librery numpy ke andar ndarray generet karta tha
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [56]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [59]:


####Numpy --- linear algebra

In [70]:
arrr1= np.random.randint([[2,3] , [4,5]])

In [71]:
arrr2= np.random.randint([[5,3] , [2,5]])

In [73]:
np.dot(arrr1, arrr2)

array([[2, 2],
       [3, 2]])

In [75]:
#same pdt
arrr1@arrr2

array([[2, 2],
       [3, 2]])